version: '3'

services:
  backend:
    labels:
        - "traefik.http.routers.backend.entrypoints=websecure" 
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=production" 
  frontend:
    command: > 
      bash -c "npm install -g serve && serve -s build --no-request-logging "
    labels:
      - "traefik.http.routers.frontend.entrypoints=websecure" 
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=production"  
  traefik:
    volumes:
      - ./Proxy/Traefik/share/:/etc/traefik #Config files
      - ./Proxy/Traefik/log:/var/log/traefik #Log files
    ports:
    - "443:443"
  test-app:
    labels:
      - "traefik.http.routers.test-app.entrypoints=websecure"
      - "traefik.http.routers.test-app.tls=true"
      - "traefik.http.routers.test-app.tls.certresolver=production"