version: '3'

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    command: >
      bash -c "dotnet dev-certs https && dotnet run"
    working_dir: /app
    network_mode: bridge
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7290
    ports:
      - "4000:7290"

  frontend:
    image: node
    command: [ "npm", "start" ]
    network_mode: bridge
    working_dir: /app
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    ports:
      - "4001:44489"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # nginx:
  #   image: nginx:latest
  #   links:
  #     - backend
  #     - frontend
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"
  # database:
  #   image: sqlite3:latest
