version: '3'

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: backend
    command: >
      bash -c "dotnet run"
    working_dir: /app
    # depends_on:
      # - database dotnet dev-certs https && 
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7290
      - url=https://api.theaterlaak.site  #Caddy config
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.theaterlaak.site`)"
      - "traefik.http.routers.backend.entrypoints=websecure" 
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=staging"  
      # - 'traefik.port=7290'
    expose:
      - 7290
    restart: unless-stopped

    
  frontend:
    image: node
    container_name: frontend
    command: [ "npm", "start" ]
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - url=https://theaterlaak.site  #Caddy config
    scale: 1
    labels:
      #Traefik config
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`theaterlaak.site`) || Host(`www.theaterlaak.site`)"
      - "traefik.http.routers.frontend.entrypoints=websecure" 
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=staging"   
      - 'traefik.backend=node'
      # - 'traefik.port=3000'
    expose:
      - 3000
    restart: unless-stopped
    
    
  traefik:
    image: "traefik:v2.9.6"
    container_name: "traefik"
    # command:
      # - "--api.dashboard=true"
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443" 
    volumes:
      - ./Proxy/Traefik/share/:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Proxy/Traefik/log:/var/log/traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" #Dashboard, remove in prod
    
    restart: unless-stopped

  # caddy:
  #   image: caddy:alpine
    
  #   volumes:
  #           - ./Proxy/Caddy/Caddyfile:/etc/caddy/Caddyfile
  #           - ./Proxy/Caddy//data:/data # Optional
  #           - ./Proxy/Caddy/config:/config # Optional
  #   ports:
  #           - "80:80"
  #           - "443:443"
  #   restart: unless-stopped
  test-app:
      image: containous/whoami:v1.3.0
      hostname: whoami
      container_name: whoami
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.test-app.rule=Host(`test.theaterlaak.site`)"
        - "traefik.http.routers.test-app.entrypoints=websecure"
        - "traefik.http.routers.test-app.tls=true"
        - "traefik.http.routers.test-app.tls.certresolver=staging"


