version: '3'

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    command: >
      bash -c "dotnet dev-certs https && dotnet run"
    # network_mode: bridge
    working_dir: /app
    depends_on:
      - database
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTPS_PORT=7290
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - 'traefik.port=7290'
    # ports:
    #   - "4000:7290"
    expose:
      - 7290
    

  frontend:
    image: node
    command: [ "npm", "start" ]
    # network_mode: bridge
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`) || Host(`www.frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - 'traefik.backend=node'
      - 'traefik.port=3000'
    # ports:
    #   - "4001:80"
    expose:
      - 3000
    

  database:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=WDPR-DB
      - MYSQL_USER=kekcoon
      - MYSQL_PASSWORD=123456
    







  traefik:
    image: "traefik:v2.9.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"

  # whoami2:
  #   image: "nginxdemos/hello"
  #   scale: 1
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami2.rule=Host(`localhost`) && Path(`/whoami2`)"
  #     - "traefik.http.routers.whoami2.entrypoints=web"