name: CI/CD pipeline

on:
  push:
    branches:
      - Stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        # Run your tests here
        echo "(Not)Running tests..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          # Run commands to deploy code to your Raspberry Pi here
          echo "Deploying..."
          ProjectDir
          docker-compose down
          ./deploy -r
          git checkout Stable
          git pull
          ./deploy
          cd ./frontend
          npm run build
          cd ../backend
          dotnet restore
          cd ..
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

